// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTOXnTAwAun_WZmkOO_qasUsnNFT1jvY',
    appId: '1:927981217000:web:a039ebdf58064385d7155d',
    messagingSenderId: '927981217000',
    projectId: 'chaw-23151',
    authDomain: 'chaw-23151.firebaseapp.com',
    storageBucket: 'chaw-23151.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-MByEA_45k-Q4gcFUpRvG13xLl83hx5s',
    appId: '1:927981217000:android:5b7b61fc6430a178d7155d',
    messagingSenderId: '927981217000',
    projectId: 'chaw-23151',
    storageBucket: 'chaw-23151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk89d_yho7Y1zZ44cnst5Nlpb8IoF1zEM',
    appId: '1:927981217000:ios:27342d90ad196aaed7155d',
    messagingSenderId: '927981217000',
    projectId: 'chaw-23151',
    storageBucket: 'chaw-23151.appspot.com',
    iosClientId: '927981217000-k2o7e9nsoevf613vciirk2bgp9dpuln3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk89d_yho7Y1zZ44cnst5Nlpb8IoF1zEM',
    appId: '1:927981217000:ios:27342d90ad196aaed7155d',
    messagingSenderId: '927981217000',
    projectId: 'chaw-23151',
    storageBucket: 'chaw-23151.appspot.com',
    iosClientId: '927981217000-k2o7e9nsoevf613vciirk2bgp9dpuln3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaw',
  );
}
